package by.etc.finaltask.controller.command;

public enum CommandType {
    AUTHORIZATION,
    REGISTRATION,
    CHANGE_LANGUAGE,
    LOGOUT,
    CREATE_COURSE,
    TEACHER_COURSE,
    SHOW_HOME_PAGE,
    SHOW_REQUEST,
    ADD_COUNT_REQUEST,
    REJECT_SUBSCRIBER,
    ACCEPT_SUBSCRIBER,
    COURSE_CREATION_PAGE,
    SHOW_COURSE,
    REMOVE_COURSE
}
